title: Patience NGELINKOTO MPIA
description: Doyenne de la Faculté des Sciences et Technologies de l’UPN et directrice générale du CREE. Professeure ordinaire en chimie et environnement.
url: https://ngelinkoto.github.io
baseurl: ""
lang: fr
email: ngelipatience@gmail.com
linkedin: https://cd.linkedin.com/in/patience-ngelinkoto-mpia-bokango-666b7784
featured_video:
  id: fSDHNtbVYeA
  url: https://www.youtube.com/watch?v=fSDHNtbVYeA
  title: "TOP VERT : La valorisation des déchets biodégradables en biogaz"
  channel: Top Congo
featured_bulletin:
  url: https://csnrdc.net/wp-content/uploads/2024/08/BULLETIN-15E-EDITIONANG1.pdf#page=14
markdown: kramdown
permalink: pretty
timezone: Africa/Kinshasa
plugins:
  - jekyll-sitemap
exclude:
  - resources
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - scripts
  - node_modules
  - package.json
  - package-lock.json
  - docs
  - .bundle
